name: CI/CD

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out project
        uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate dataset output
        run: python generate.py

      - name: Upload generated file
        uses: actions/upload-artifact@v2
        with:
          name: dataset
          path: ./output/shots.yml
          retention-days: 1

  deploy:
    if: success() && github.ref_type == 'tag'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download dataset
        uses: actions/download-artifact@v2
        id: download
        with:
          name: dataset
          path: ~/dataset

      - name: Commit dataset
        run: |
          cd ${{ steps.download.outputs.download-path }}
          git init
          git add .
          git commit -m "Update dataset"

      - name: Push to target repository
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'ref/heads/prod'
          directory: ${{ steps.download.outputs.download-path }}
          force: true